=pod

=head1 NAME

Function - deal with pieces of reusable code.

=head1 SYNOPSIS

	var x = function(a,b) {
		this.a = a;
		this.b = b;
	};
	
	x.apply(null, ["a", "b"]);
	
=head1 DESCRIPTION

A function is a piece of reusable code that takes a group of arguments, performs statements, and then returns some value.

=head1 METHODS

=head2 Inherited

From Object.prototype:
hasOwnProperty, isPrototypeOf, propertyIsEnumerable, unwatch, watch

=head2 Constructor()

*** Not Implementable In Standard JavaScript

This creates a new function object.

=head2 toString() Returns String

*** Not Implementable In Standard JavaScript

This returns a string representation of the function.

=head2 apply(Object thisArg, Array argsArray) Returns Any

=head2 call(Object thisArg, *@argsArray) Returns Any

=head2 toSource() Returns String

Returns a source representation of the function.

=head1 AUTHOR

Jhuni, <jhuni_x@yahoo.com>

=head1 COPYRIGHT

Public Domain

=cut

