=head1 NAME

sudoko.model.solver.solve - a javascript function that solves sudoko.

=head1 SYNOPSIS

var solvedPosition = sudoko.model.solver.solve(new Grid( [
	7,9,0,  0,0,0,  3,0,0,
	0,0,0,  0,0,6,  9,0,0,
	8,0,0,  0,3,0,  0,7,6,
	
	0,0,0,  0,0,5,  0,0,2,
	0,0,5,  4,1,8,  7,0,0,
	4,0,0,  7,0,0,  0,0,0,
	
	6,1,0,  0,9,0,  0,0,8,
	0,0,2,  3,0,0,  0,0,0,
	0,0,9,  0,0,0,  0,5,4
], new tbsize(9,9) )    );

=head1 DESCRIPTION

This package is actually a single function solve() which returns
a solved sudoko grid from an unsolved one. This will
output a grid such that it has no zeros in it.

=head1 AUTHOR

Jhuni, <jhuni_x@yahoo.com>

=head1 COPYRIGHT

GNU General Public License

