if(typeof CKIT=='undefined')CKIT={};if(typeof CKIT.Utils=='undefined')CKIT.Utils={};CKIT.Utils.Base={assign:function(name,obj){var isUndefinedYet=false;var spaces=name.split('.');var parent=window;var j=spaces.length;for(var i=0;i<j-1;i++){if(typeof parent[spaces[i]]=='undefined'){isUndefinedYet=true;}else{parent=parent[spaces[i]];}
if(isUndefinedYet){parent=parent[spaces[i]]={};}}
parent[spaces[j-1]]=obj;return true;},update:function(obj,props){for(var i in props){obj[i]=props[i];}
return obj;},identity:function(value){return value;}};CKIT.Utils.Base.assign('CKIT.Conditions.General',{isEqualTo:function(cvalue){return function(a){return a==cvalue;};},isNull:function(cvalue){return(cvalue===null);},isDef:function(cvalue){return(typeof cvalue!='undefined');},isNotDef:function(cvalue){return(typeof cvalue=='undefined');},not:function(condition){return function(cvalue){return!condition(cvalue);};}});CKIT.Utils.Base.assign('CKIT.Class',(function(){var pkg=function(){};pkg.create=function(props){if(!props.Onload){props.Onload=function(){};}
if(!props.Extends){props.Extends=[];}
var len=props.Has.length;var isBase=true;var myclass=function(){for(var i=0;i<len;i++){this[props.Has[i]]=arguments[i];}
if(isBase){this.Onload();}};CKIT.Utils.Base.update(myclass,{create:function(obj){isBase=false;var rval=new myclass();isBase=true;CKIT.Utils.Base.update(rval,obj);rval.Onload();return rval;},assign:function(pkg,obj){CKIT.Utils.Base.assign(pkg,this.create(obj));},addMethods:function(methods){CKIT.Utils.Base.update(myclass.prototype,methods);},extend:function(props){CKIT.Utils.Base.update(myclass,props);}});for(var i=0,j=props.Extends.length;i<j;i++){CKIT.Utils.Base.update(myclass.prototype,props.Extends[i].prototype);}
CKIT.Utils.Base.update(myclass.prototype,props);return myclass;};pkg.assign=function(name,props){CKIT.Utils.Base.assign(name,this.create(props));};return pkg;})());CKIT.Class.assign('CKIT.TruthTable',{Has:['t','f'],all:function(){return this.f==0;},none:function(){return this.t==0;},any:function(){return this.t!=0;},notall:function(){return this.f!=0;},one:function(){return this.t==1;},addCondition:function(cbool){var inc=(cbool)?1:0;this.t+=inc;this.f+=1-inc;}});(function(){var $CG=CKIT.Conditions.General;var $B=CKIT.Utils.Base;CKIT.Class.assign('CKIT.Iter',{Has:['next','restart'],map:function(func){var rval=[];var next=this.next();while(!pkg.stop){rval[rval.length]=func(next);next=this.next();}
this.restart();pkg.stop=false;return rval;},toArray:function(){return this.map($B.identity);},forEach:function(func){var next=this.next();while(!pkg.stop){func(next);next=this.next();}
this.restart();pkg.stop=false;return this;},condition:function(condition){var rval=new CKIT.TruthTable(0,0);this.forEach(function(i){rval.addCondition(condition(i));});return rval;},repeating:function(){var rval=new CKIT.TruthTable(0,0);var pastValues=[this.next()];this.forEach(function(i){rval.addCondition(pkg.array(pastValues).condition($CG.isEqualTo(i)).any());pastValues[pastValues.length]=i;});return rval;},reduce:function(operator){var last=this.next();this.forEach(function(i){last=operator(last,i);});return last;}});var pkg=CKIT.Iter;CKIT.Iter.extend({stop:false,repeat:function(value,stop){var start=0;return new pkg(function(){pkg.stop=!(stop>start++);return value;},function(){start=0;});},array:function(array){var i=0;return new pkg(function(){pkg.stop=!(i<array.length);return array[i++];},function(){i=0;});}});})();CKIT.Class.assign('CKIT.List',{Has:['v'],Extends:[CKIT.Iter],Onload:function(){this.elems=this.v.length;this.iterIndex=0;var self=this;this.getIndex=function(index){return self.v[index];};this.setIndex=function(index,value){self.v[index]=value;};},'next':function(){CKIT.Iter.stop=!(this.iterIndex<this.elems);return this.getIndex(this.iterIndex++);},'restart':function(){this.iterIndex=0;},'setLength':function(newLength){this.elems=newLength;},'swapIndexes':function(start,end){var endingValue=this.getIndex(end);this.setIndex(end,this.getIndex(start));this.setIndex(start,endingValue);return this;},'removeIndex':function(index){var rval=this.getIndex(index);for(var i=index,l=this.elems;i<l;i++){this.setIndex(i,this.getIndex(i+1));}
this.setLength(this.elems-1);return rval;},'shift':function(){return this.removeIndex(0);},'pop':function(){return this.removeIndex(this.elems-1);},'push':function(){this.setLength(this.elems+arguments.length);var oldl=this.elems-arguments.length;for(var i=0,l=arguments.length;i<l;i++){this.setIndex(oldl+i,arguments[i]);}
return this.elems;},'unshift':function(){var arglen=arguments.length;this.setLength(this.elems+arguments.length);for(var i=this.elems-arglen-1;i>=0;i--){this.setIndex(i+arglen,this.getIndex(i));}
for(var i=0;i<arglen;i++){this.setIndex(i,arguments[i]);}
return this.elems;},'removeIf':function(condition){for(var i=0,l=this.elems;i<l;i++){if(condition(this.getIndex(i))){this.removeIndex(i);i--;}}
return this;},'firstIndex':function(condition){for(var i=0,l=this.elems;i<l;i++){if(condition(this.getIndex(i))){return i;}}
return-1;},'lastIndex':function(condition){for(var i=this.elems;i>=0;i--){if(condition(this.getIndex(i))){return i;}}
return-1;},'indexOf':function(val){for(var i=0,l=this.elems;i<l;i++){if(this.getIndex(i)==val){return i;}}
return-1;},'lastIndexOf':function(val){for(var i=this.elems;i>=0;i--){if(this.getIndex(i)==val){return i;}}
return-1;},'getRandomChoice':function(){return this.getIndex(Math.floor(Math.random()*this.elems));},'pick':function(pickCount){},'reverse':function(){var start=0;var end=this.elems-1;while(start<end){this.swapIndexes(start++,end--);}
return this;},'shuffle':function(){var i=this.elems;while(--i){this.swapIndexes(i,Math.floor(Math.random()*(i+1)));}
return this;},'uniq':function(){var ccg=CKIT.Conditions.General;var pastvalues=[];for(var i=0,l=this.elems;i<l;i++){var currentValue=this.getIndex(i);if(CKIT.Iter.array(pastvalues).condition(ccg.isEqualTo(currentValue)).any()){this.removeIndex(i);continue;}
pastvalues[pastvalues.length]=currentValue;}
return this;},'setEveryValueTo':function(value){for(var i=0,l=this.elems;i<l;i++){this.setIndex(i,value);}},'setValuesToList':function(list){for(var i=0,l=list.elems;i<l;i++){this.setIndex(i,list.getIndex(i));}},'isEqualTo':function(value){var rval=new CKIT.TruthTable(0,0);for(var i=0,l=this.elems;i<l;i++){rval.addCondition(this.getIndex(i)==value);}
return rval;}});CKIT.Class.assign('CKIT.BitList',{Has:['elems'],Extends:[CKIT.List],Onload:function(){this.elems=(typeof this.elems=='undefined')?0:this.elems;this.bits=[];this.iterIndex=0;},getIndex:function(index){var field=this.bits[Math.floor(index/30)];var fieldBit=index%30;return((field&1<<index)>>index);},setIndex:function(bit,value){this.elems=(bit+1>this.elems)?bit+1:this.elems;var field=Math.floor(bit/30);if(value==1){this.bits[field]=this.bits[field]|1<<(bit%30);}else{this.bits[field]=this.bits[field]&~(1<<bit);}},toggleIndex:function(index){var field=Math.floor(index/30);this.bits[field]=this.bits[field]^1<<(index%30);},truths:function(){var rval=new CKIT.TruthTable(0,0);var len=this.elems;for(var i=0;i<len;i++){var bit=this.getIndex(i);rval.t+=bit;rval.f+=1-bit;}
return rval;},toString:function(){var rval='';var len=this.elems;for(var i=0;i<len;i++){rval+=this.getIndex(i);}
return rval;}});CKIT.Class.assign('CKIT.CharList',{Has:['str'],Extends:[CKIT.List],Onload:function(){this.elems=this.str.length;this.iterIndex=0;},getIndex:function(index){return this.str.charAt(index);},setIndex:function(index,value){this.str=this.str.substr(0,index)+value+this.str.substr(index+1);},toString:function(){var rval="";for(var i=0,l=this.elems;i<l;i++){rval+=this.getIndex(i);}
return rval;}});CKIT.Class.assign('CKIT.Code',{Has:['str'],Extends:[CKIT.CharList],Onload:function(){this.elems=this.str.length;this.iterIndex=0;},eval:function(){eval(this.str);}});CKIT.Class.assign('CKIT.Sequence',{Has:['next','restart'],Extends:[CKIT.Iter],sum:function(){return this.reduce(function(a,b){return a+b;});}});CKIT.Sequence.extend({range:function(start,stop,step){return new CKIT.Sequence(function(){CKIT.Iter.stop=(step>0&&start>=stop)||(step<0&&start<=stop);var rval=start;start+=step;return rval;},function(){start=0;});},slice:function(start,stop){return CKIT.Sequence.range(start,stop,1);},upto:function(stop){return CKIT.Sequence.slice(0,stop);}});CKIT.Class.assign('CKIT.NumList',{Has:['v'],Extends:[CKIT.List,CKIT.Sequence],Onload:function(){this.elems=this.v.length;this.iterIndex=0;},getIndex:function(index){return this.v[index];},setIndex:function(index,value){this.v[index]=value;},maxIndex:function(){var highestYet=this.getIndex(0);var rval=0;for(var i=0,l=this.elems;i<l;i++){var currentValue=this.getIndex(i);if(currentValue>highestYet){highestYet=currentValue;rval=i;}}
return rval;}});

CKIT.Utils.Base.extendByPairs = function(obj, pairs) {
	
	var keys = pairs[0];
	var values = pairs[1];
	
	for( var i = 0, l = values.length; i < l; i++ ) {
		obj[keys[i]] = values[i];
	}
	
	return obj;
	
};

//CKIT.Class.assign = function(ns,obj) { alert( "Fix the following ns from CKIT.Class: " + ns ); };
